spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmp01?serverTimezone=Asia/Seoul
    username: admin
    password: 1234

  # Oauth
  profiles:
    include: oauth

server:
  servlet:
    encoding:
      force-response: true